USE DB_LGPD;

-- ROW LEVEL SECURITY
-- PARA GERENCIAR FACILMENTE AS PERMISSÕES EM SEUS BANCOS DE DADOS, O SQL SERVER FORNECE VÁRIAS FUNÇÕES , QUE SÃO ENTIDADES DE SEGURANÇA QUE AGRUPAM OUTRAS ENTIDADES.
-- ELAS SÃO COMO GRUPOS NO SISTEMA OPERACIONAL MICROSOFT WINDOWS. AS FUNÇÕES DE NÍVEL DE BANCO DE DADOS SÃO PERMITIDAS EM TODO BANCO DE DADOS EM SEUS ESCOPOS DE PERMISSÕES.

-- EXEMPLO
-- CRIANDO ROLES PERSONALIZADAS PARA ACESSO
CREATE ROLE VENDEDOR_COM_ACESSO;
CREATE ROLE VENDEDOR_SEM_ACESSO;
CREATE ROLE VENDEDOR_SEM_MASK;
-- CRIANDO USUÁRIOS DE EXEMPLO
CREATE USER USUARIO1 WITHOUT LOGIN;
CREATE USER USUARIO2 WITHOUT LOGIN;
CREATE USER USUARIO3 WITHOUT LOGIN;

-- ADICIONANDO USUÁRIOS ÀS RESPECTIVAS ROLES
EXEC SP_ADDROLEMEMBER 'VENDEDOR_COM_ACESSO', 'USUARIO1';
EXEC SP_ADDROLEMEMBER 'VENDEDOR_COM_ACESSO', 'USUARIO2';
EXEC SP_ADDROLEMEMBER 'VENDEDOR_SEM_ACESSO', 'USUARIO3';
EXEC SP_ADDROLEMEMBER 'VENDEDOR_SEM_MASK', 'USUARIO1';

-- REMOVENDO USUÁRIOS ÀS RESPECTIVAS ROLES
-- EXEC SP_DROPROLEMEMBER 'VENDEDOR_COM_ACESSO', 'USUARIO1';
-- EXEC SP_DROPROLEMEMBER 'VENDEDOR_COM_ACESSO', 'USUARIO2';
-- EXEC SP_DROPROLEMEMBER 'VENDEDOR_SEM_ACESSO', 'USUARIO3';
-- EXEC SP_DROPROLEMEMBER 'VENDEDOR_SEM_MASK', 'USUARIO1';

-- CONCEDENDO ACESSO DE LEITURA ÀS RESPECTIVAS ROLES
GRANT SELECT ON CLIENTE TO VENDEDOR_COM_ACESSO;
GRANT SELECT ON CLIENTE TO VENDEDOR_SEM_MASK;
-- CONCEDENDO ACESSO DE LEITURA ÀS RESPECTIVAS ROLES (UNMASK)
GRANT UNMASK TO VENDEDOR_SEM_MASK;
-- NEGANDO ACESSO DE LEITURA À RESPECTIVA ROLE
DENY SELECT ON CLIENTE TO VENDEDOR_SEM_ACESSO;

-- TESTE DE ACESSO USUÁRIO1
EXEC AS USER = 'USUARIO1';
SELECT * FROM CLIENTE;
REVERT;

-- TESTE DE ACESSO USUÁRIO2
EXEC AS USER = 'USUARIO2';
SELECT * FROM CLIENTE;
REVERT;

-- TESTE DE ACESSO USUÁRIO3
EXEC AS USER = 'USUARIO3';
SELECT * FROM CLIENTE;
REVERT;