USE SALES;

-- STORED PROCEDURES
-- UM PROCEDIMENTO ARMAZENADO É UM TIPO ESPECIAL DE SCRIPT.
-- OS PROCEDIMENTOS SÃO SALVOS EM UM SERVIDOR DE BANCO DE DADOS PARA APERFEIÇOAR O DESEMPENHO E A CONSISTÊNCIA DAS TAREFAS REPETITIVAS.
-- PODEM SER USADOS PARA AS SEGUINTES TAREFAS:
-- CONTROLAR AUTORIZAÇÃO DE ACESSO.
-- CRIAR UM CAMINHO DE AUDITORIA DE ATIVIDADES EM TABELAS DE BANCOS DE DADOS.
-- SEPARAR INSTRUÇÕES DE DEFINIÇÃO E DE MANIPULAÇÃO DE DADOS RELATIVAS A UM BANCO DE DADOS DAS APLICAÇÕES QUE O ACESSAM.
-- SÃO OBRIGATÓRIOS OS COMANDOS DE INÍCIO E TÉRMINO DE BLOCO, BEGIN...END.

-- EXEMPLO 1
-- CRIANDO PROCEDURE PARA RETORNAR CONTEÚDO ESTÁTICO
CREATE PROCEDURE SP_HELLO AS
BEGIN
	SELECT 'HELLO WORLD!'
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_HELLO;


-- EXEMPLO 2
-- CRIANDO PROCEDURE PARA RETORNAR TEXTO ATRAVÉS DE PARÂMETRO
CREATE PROCEDURE SP_RETORNO (@TEXTO VARCHAR(50)) AS
BEGIN
	SELECT 'O TEXTO INFORMADO: ' + @TEXTO
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_RETORNO 'É ESTE!';


-- EXEMPLO 3
-- CRIANDO PROCEDURE PARA RETORNAR MENSAGEM DE BOAS VINDAS AO USUÁRIO LOGADO
CREATE PROCEDURE SP_BOAS_VINDAS AS
BEGIN
	PRINT 'SEJA BEM-VINDO ' + SYSTEM_USER
		IF (DATEPART(HOUR, GETDATE())<12)
			PRINT 'BOM DIA!!!'
		ELSE IF (DATEPART(HOUR, GETDATE())>=12 AND DATEPART(HOUR, GETDATE())<=18)
			PRINT 'BOA TARDE!!!'
		ELSE
			PRINT 'BOA NOITE!!!'
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_BOAS_VINDAS;


-- EXEMPLO 4
-- CRIANDO PROCEDURE PARA CALCULAR QUADRADO
CREATE PROCEDURE SP_QUADRADO @NUM INT AS
BEGIN
	SELECT @NUM * @NUM AS QUADRADO
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_QUADRADO 5;


-- EXEMPLO 5
-- CRIANDO PROCEDURE PARA CALCULAR CUBO
CREATE PROCEDURE SP_CUBO @NUM INT AS
BEGIN
	SELECT @NUM * @NUM * @NUM AS CUBO
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_CUBO 5;


-- EXEMPLO 6
-- CRIANDO PROCEDURE PARA CALCULAR IMC (ÍNDICE DE MASSA CORPORAL)
CREATE PROCEDURE SP_IMC @PESO DECIMAL(10, 2), @ALTURA DECIMAL(10, 2) AS
BEGIN
	DECLARE @IMC DECIMAL(10, 2);
	SET @IMC = @PESO / (@ALTURA * @ALTURA);
		IF @IMC < 17
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' MUITO ABAIXO DO PESO.'
			END
		ELSE IF @IMC >= 17 AND @IMC <= 18.49
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' ABAIXO DO PESO.'
			END
		ELSE IF @IMC >= 18.5 AND @IMC <= 24.99
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' PESO NORMAL.'
			END
		ELSE IF @IMC >= 25 AND @IMC <= 29.99
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' ACIMA DO PESO.'
			END
		ELSE IF @IMC >= 30 AND @IMC <= 34.99
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' OBESIDADE I.'
			END
		ELSE IF @IMC >= 35 AND @IMC <= 39.99
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' OBESIDADE II (SEVERA).'
			END
		ELSE IF @IMC >= 40
			BEGIN
				PRINT 'SEU IMC É ' + CAST(@IMC AS VARCHAR(20)) + ' OBESIDADE III (MÓRBIDA).'
			END
END;
-- EXECUTANDO PROCEDURE
EXECUTE SP_IMC 80, 1.85;