-- CRIANDO DATABASE
CREATE DATABASE SALES
ON (NAME = SALES_DAT, FILENAME = 'C:\TEMP\DATA\SALES.MDF', SIZE = 50MB, MAXSIZE = 500MB, FILEGROWTH = 10MB)  
LOG ON (NAME = SALES_LOG, FILENAME = 'C:\TEMP\DATA\SALES.LDF', SIZE = 20MB, MAXSIZE = 200MB, FILEGROWTH = 10MB)
GO
USE SALES;

-- CRIANDO TABELAS
CREATE TABLE CIDADE
	(
	ID_CIDADE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME_CIDADE VARCHAR(60)  NOT NULL,
	UF VARCHAR(2) NOT NULL
	);

CREATE TABLE CATEGORIA
	(
	ID_CATEGORIA INT IDENTITY(1,1)NOT NULL PRIMARY KEY,
	NOME_CATEGORIA VARCHAR(20) NOT NULL
	);

CREATE TABLE UNIDADE
	(
	ID_UNIDADE VARCHAR(3) NOT NULL PRIMARY KEY,
	DESC_UNIDADE VARCHAR(25) NOT NULL
	);

CREATE TABLE CLIENTE
	(ID_CLIENTE INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME_CLIENTE VARCHAR(60) NOT NULL,
	ENDER VARCHAR(60) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CIDADE INT NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CONSTRAINT FK_CLI1 FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
	);

CREATE TABLE VENDEDORES
	(
	ID_VENDEDOR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME_VENDEDOR VARCHAR(60) NOT NULL ,
	SALARIO DECIMAL(10,2) NOT NULL
	);

CREATE TABLE PRODUTOS 
	(
    ID_PROD INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    NOME_PRODUTO VARCHAR(50) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
	ID_UNIDADE VARCHAR(3) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
	CONSTRAINT FK_MAT1 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT FK_MAT2 FOREIGN KEY (ID_UNIDADE) REFERENCES UNIDADE(ID_UNIDADE)
    );

CREATE TABLE VENDAS
	(
    NUM_VENDA INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    DATA_VENDA DATETIME NOT NULL,
    ID_CLIENTE INT NOT NULL,
	ID_VENDEDOR INT NOT NULL,
	STATUS CHAR(1) NOT NULL DEFAULT('N'), -- N NORMAL / C CANCELADA
	CONSTRAINT FK_VND1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_VND2 FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR)
    );

CREATE TABLE VENDA_ITENS
	(
	NUM_VENDA INT NOT NULL,
	NUM_SEQ INT NOT NULL,
	ID_PROD INT NOT NULL,
	QTDE DECIMAL(10,2) NOT NULL,
	VAL_UNIT DECIMAL(10,2) NOT NULL,
	VAL_TOTAL DECIMAL(10,2),
	CONSTRAINT FK_VNDIT1 FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS(ID_PROD),
	CONSTRAINT FK_VNDIT2 FOREIGN KEY (NUM_VENDA) REFERENCES VENDAS(NUM_VENDA),
	CONSTRAINT PK_VNDIT1 PRIMARY KEY (NUM_VENDA,NUM_SEQ)
	);

-- ADICIONANDO CHAVE ESTRANGEIRA
-- ALTER TABLE VENDA_ITENS
-- ADD FOREIGN KEY (ID_PROD) REFERENCES PRODUTOS(ID_PROD); 

-- ALTER TABLE VENDA_ITENS
-- ADD FOREIGN KEY (NUM_VENDA) REFERENCES VENDAS(NUM_VENDA);

-- CRIANDO INDEX
CREATE INDEX IX_VENDAS1 ON VENDAS(DATA_VENDA);
CREATE INDEX IX_VENDAS2 ON VENDAS(ID_CLIENTE,ID_VENDEDOR);

-- RENOMEANDO CAMPO DA TABELA
EXEC SP_RENAME 'CLIENTE.ENDER', 'ENDERECO', 'COLUMN';

-- ALTERANDO TIPO DA COLUNA
ALTER TABLE CLIENTE ALTER COLUMN ENDERECO VARCHAR(80);

-- ADICIONANDO NOVO CAMPO NA TABELA 
ALTER TABLE VENDEDORES ADD GENERO CHAR(1); 
 
-- EXCLUINDO CAMPO DA COLUNA
ALTER TABLE VENDEDORES DROP COLUMN GENERO; 

-- EXCLUINDO CHAVE ESTRANGEIRA
-- ALTER TABLE VENDAS
-- DROP CONSTRAINT FK_VND1;
   
-- RENOMEANDO TABELA
EXEC SP_RENAME 'VENDEDORES','FUNC';
EXEC SP_RENAME 'FUNC','VENDEDORES';

-- EXCLUINDO DATABASE
-- DROP DATABASE SALES; 

-- EXCLUINDO TABELA
-- DROP TABLE VENDEDORES;

-- CRIANDO VIEW
CREATE VIEW V_VENDEDORES
	AS
	SELECT * FROM VENDEDORES;

-- ALTERANDO VIEW
ALTER VIEW V_VENDEDORES
	AS 
	SELECT ID_VENDEDOR,NOME_VENDEDOR FROM VENDEDORES;

-- EXCLUINDO VIEW
DROP VIEW V_VENDEDORES; 

-- CRIANDO INDEX
CREATE INDEX IX_VEND1 ON VENDEDORES (NOME_VENDEDOR);

-- EXCLUINDO INDEX
DROP INDEX IX_VEND1 ON VENDEDORES;

-- EXCLUINDO PROCEDURE
-- DROP PROCEDURE PROC_SALARIO;

-- EXCLUINDO FUNÇÃO
-- DROP FUNCTION VEND_SALARIO;

-- EXCLUINDO TRIGGER
-- DROP TRIGGER TRIG_VEND_SALARIO;


-- CRIANDO TABELA COM BASE EM UMA EXISTENTE
SELECT * INTO SALES_BK FROM SALES;

-- VERIFICANDO OS DADOS
SELECT * FROM SALES_BK;

-- REALIZANDO TRUNCATE PARA APAGAR TODOS OS DADOS DA TABELA
TRUNCATE TABLE SALES_BK;

-- CRIANDO TABELA TEMPORÁRIA COM BASE EM UMA EXISTENTE
SELECT * INTO #BK_SALES FROM SALES;

-- VERIFICANDO OS DADOS NA TABELA TEMPORÁRIA
SELECT * FROM #BK_SALES;

-- APAGANDO OS DADOS DA TABELA
TRUNCATE TABLE SALES;

-- INSERINDO OS DADOS NA TABELA COM BASE NOS DADOS DA TABELA TEMPORÁRIA
INSERT INTO SALES
SELECT * FROM #BK_SALES;

-- VERIFICANDO OS DADOS 
SELECT * FROM SALES;