USE SALES;

-- EXEMPLO SUBQUERYS
SELECT A.NOME_VENDEDOR,
	   A.SALARIO
FROM VENDEDORES AS A
WHERE SALARIO IN
	(SELECT MIN(SALARIO) FROM VENDEDORES);

-- EXEMPLO SUBQUERYS
SELECT A.NOME_PRODUTO,
	   A.PRECO,
	   (SELECT B.NOME_CATEGORIA FROM CATEGORIA AS B WHERE A.ID_CATEGORIA = B.ID_CATEGORIA) AS NOME_CATEGORIA
FROM PRODUTOS AS A;

-- EXEMPLO SUBQUERYS
SELECT A.NOME_PRODUTO,
	   A.PRECO,
	   (SELECT B.NOME_CATEGORIA FROM CATEGORIA AS B WHERE A.ID_CATEGORIA = B.ID_CATEGORIA) AS NOME_CATEGORIA,
	   (SELECT C.DESC_UNIDADE FROM UNIDADE AS C WHERE C.ID_UNIDADE = A.ID_UNIDADE) AS TIPO_UNIDADE
FROM PRODUTOS AS A;

-- EXEMPLO SUBQUERYS
SELECT A.ID_CLIENTE,
	   A.NOME_CLIENTE,
	   (SELECT COUNT(*) FROM VENDAS AS B WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS QTD_VENDAS,
	   (SELECT AVG(B.VALOR_TOTAL) FROM VENDAS AS B WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS MEDIA,
	   (SELECT MIN(B.VALOR_TOTAL) FROM VENDAS AS B WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS MENOR_TICKET,
	   (SELECT MAX(B.VALOR_TOTAL) FROM VENDAS AS B WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS MAIOR_TICKET,
	   (SELECT SUM(B.VALOR_TOTAL) FROM VENDAS AS B WHERE A.ID_CLIENTE = B.ID_CLIENTE) AS TOTAL
FROM CLIENTE AS A;