USE SALES;
GO

-- CRIANDO LOGIN
EXEC MASTER.dbo.SP_ADDLOGIN 'USERTESTE','SENHATESTE';

-- DEFININDO ACESSO DO LOGIN COMO USUÁRIO DO BANCO DE DADOS ATUAL
EXEC SP_GRANTDBACCESS 'USERTESTE';

-- REVOGANDO ACESSO DO LOGIN
-- EXEC SP_REVOKEDBACCESS 'USERTESTE';

-- CONCEDENDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
GRANT UPDATE ON CLIENTE TO USERTESTE;
-- CONCEDENDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
GRANT INSERT ON CLIENTE TO USERTESTE;
-- CONCEDENDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
GRANT SELECT ON CLIENTE TO USERTESTE;
-- CONCEDENDO ACESSO DE DELETE PARA USUÁRIO USERTESTE
GRANT DELETE ON CLIENTE TO USERTESTE;

-- CRIANDO PROCEDURE DE EXEMPLO
CREATE PROCEDURE TEST_PROC
AS
SELECT * FROM VENDEDORES;
-- EXECUTANDO PROCEDURE
EXEC TEST_PROC;
-- CONCEDENDO ACESSO PARA EXECUTAR PROC TEST_PROC PARA USUÁRIO USERTESTE
GRANT EXECUTE ON TEST_PROC TO USERTESTE;

-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;
-- ALTERANDO USUÁRIO LOGADO
SETUSER 'USERTESTE';
-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;

-- EXECUTANDO PROCEDURE COM USUÁRIO USERTESTE
EXEC TEST_PROC;

-- TESTANDO SELECT COM USUÁRIO USERTESTE
SELECT * FROM VENDEDORES;

-- TESTANDO INSERT COM USUÁRIO USERTESTE
INSERT INTO VENDEDORES VALUES ('Will Smith','2200','A');

-- TESTANDO UPDATE COM USUÁRIO USERTESTE
UPDATE VENDEDORES SET NOME_VENDEDOR = 'Marilyn Monroe'
WHERE ID_VENDEDOR = '5';

-- TESTANDO DELETE COM USUÁRIO USERTESTE
DELETE FROM VENDEDORES
WHERE ID_VENDEDOR = '6';


-- ALTERANDO USUÁRIO LOGADO PARA O ANTERIOR
SETUSER;
-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;
