USE SALES;
GO

-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;

-- REVOGANDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
REVOKE UPDATE ON CLIENTE TO USERTESTE;
-- REVOGANDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
REVOKE INSERT ON CLIENTE TO USERTESTE;
-- REVOGANDO ACESSO DE UPDATE PARA USUÁRIO USERTESTE
REVOKE SELECT ON CLIENTE TO USERTESTE;
-- REVOGANDO ACESSO DE DELETE PARA USUÁRIO USERTESTE
REVOKE DELETE ON CLIENTE TO USERTESTE;
-- REVOGANDO EXECUÇÃO DE TEST_PROC PARA USUÁRIO USERTESTE
REVOKE EXECUTE ON TEST_PROC TO USERTESTE;

-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;
-- ALTERANDO USUÁRIO LOGADO
SETUSER 'USERTESTE';
-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;

-- EXECUTANDO PROCEDURE COM USUÁRIO USERTESTE
EXEC TEST_PROC;

-- TESTANDO SELECT COM USUÁRIO USERTESTE
SELECT * FROM VENDEDORES;

-- TESTANDO INSERT COM USUÁRIO USERTESTE
INSERT INTO VENDEDORES VALUES ('Wesley Snipes','2500','A');

-- TESTANDO UPDATE COM USUÁRIO USERTESTE
UPDATE VENDEDORES SET NOME_VENDEDOR = 'Arnold Schwarzenegger'
WHERE ID_VENDEDOR = '5';

-- TESTANDO DELETE COM USUÁRIO USERTESTE
DELETE FROM VENDEDORES
WHERE ID_VENDEDOR = '6';


-- ALTERANDO USUÁRIO LOGADO PARA O ANTERIOR
SETUSER;
-- VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER;