USE SALES;

-- OPENROWSET
-- INCLUI TODAS AS INFORMAÇÕES DE CONEXÃO EXIGIDAS PARA ACESSAR DADOS REMOTOS DE UMA FONTE DE DADOS OLE DB.
-- ESTE MÉTODO É UMA ALTERNATIVA PARA ACESSAR TABELAS EM UM SERVIDOR VINCULADO E SE TRATA DE UM MÉTODO DE USO ÚNICO E AD HOC PARA CONEXÃO E ACESSO A DADOS REMOTOS POR MEIO DE OLE DB.
-- A FUNÇÃO OPENROWSET PODE SER REFERENCIADA NA CLÁUSULA FROM DE UMA CONSULTA COMO SE FOSSE UM NOME DE TABELA.
-- A FUNÇÃO OPENROWSET TAMBÉM PODE SER REFERENCIADA COMO A TABELA DE DESTINO DE UMA INSTRUÇÃO INSERT, UPDATE OU DELETE, SUJEITO ÀS FUNCIONALIDADES DO PROVEDOR OLE DB.
-- EMBORA A CONSULTA POSSA RETORNAR VÁRIOS CONJUNTOS DE RESULTADOS, OPENROWSET RETORNA SOMENTE O PRIMEIRO DELES.

-- EXEMPLO

-- CONFIGURAÇÃO PARA ATIVAR AD HOC DISTRIBUÍDA
SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 1;
RECONFIGURE;
SP_CONFIGURE 'AD HOC DISTRIBUTED QUERIES', 1;
RECONFIGURE;

-- CONFIGURAÇÃO PARA DESATIVAR AD HOC DISTRIBUÍDA
SP_CONFIGURE 'SHOW ADVANCED OPTIONS', 0;
RECONFIGURE;
SP_CONFIGURE 'AD HOC DISTRIBUTED QUERIES', 0;
RECONFIGURE;

-- OPENROWSET (SELECT)
SELECT * FROM
OPENROWSET ('SQLNCLI', 'SERVER = FELIPEBACELO\SQLEXPRESS; TRUSTED_CONNECTION = YES;', 
			'SELECT * FROM SALES.DBO.ESTOQUE');

-- OPENROWSET (INSERT)
INSERT OPENROWSET ('SQLNCLI', 'SERVER = FELIPEBACELO\SQLEXPRESS; TRUSTED_CONNECTION = YES;', 
				   'SELECT * FROM SALES.DBO.ESTOQUE') VALUES (21, 'SCANNER', 250);

-- OPENROWSET (UPDATE)
UPDATE OPENROWSET ('SQLNCLI', 'SERVER = FELIPEBACELO\SQLEXPRESS; TRUSTED_CONNECTION = YES;', 
				   'SELECT * FROM SALES.DBO.ESTOQUE WHERE ID_PROD = 21')
SET PRECO = 300;

-- OPENROWSET (DELETE)
DELETE OPENROWSET ('SQLNCLI', 'SERVER = FELIPEBACELO\SQLEXPRESS; TRUSTED_CONNECTION = YES;', 
				   'SELECT * FROM SALES.DBO.ESTOQUE WHERE ID_PROD = 21');