USE SALES;

-- BULK
-- O COMANDO BULK INSERT É UTILIZADO PARA COPIAR/IMPORTAR DADOS DE UM ARQUIVO DE TEXTO OU NATIVO DO SQL SERVER, TAMBÉM CHAMADOS DE FLAT FILE.

-- PRINCIPAIS PARÂMETROS
-- CODEPAGE: DEFINE A PÁGINA DE CÓDIGOS A SER USADA NA IMPORTAÇÃO E, POR CONSEQUÊNCIA, SE OS CARACTERES VÊM ACENTUADOS OU NÃO (ACP, OEM, RAW, CODE_PAGE).
-- DATAFILETYPE: DEFINE QUE A IMPORTAÇÃO UTILIZARÁ O VALOR DE TIPO DE ARQUIVO DE DADOS ESPECIFICADO (CHAR, NATIVE, WIDECHAR, WIDENATIVE).
-- FIELDTERMINATOR: CARACTERE UTILIZADO PARA SEPARAR UMA COLUNA DA OUTRA. (POR DEFAULT É O CARACTERE [TAB] TAMBÉM REPRESENTADO POR \t).
-- ROWTERMINATOR: CARACTERE UTILIZADO PARA SEPARAR UMA LINHA DA OUTRA (POR DEFAULT É O CARACTERE [ENTER] TAMBÉM REPRESENTADO POR \n).
-- MAXERRORS: DEFINE A QUANTIDADE MÁXIMA DE ERROS QUE PODE OCORRER NUMA IMPORTAÇÃO DE DADOS.
-- FIRE_TRIGGERS: SE INFORMADO, DISPARA AS TRIGGERS NA EXECUÇÃO DO COMANDO (POR DEFAULT NÃO DISPARA).
-- KEEP IDENTITY: SE INFORMADO, IMPEDE QUE A NUMERAÇÃO AUTOMÁTICA (COLUNA IDENTITY DA TABELA) SEJA USADA.
-- FIRSTROW: DEFINE QUAL SERÁ A PRIMEIRA LINHA IMPORTADA.
-- LASTROW: DEFINE QUAL SERÁ A ÚLTIMA LINHA IMPORTADA.


-- EXEMPLO
-- CRIANDO TABELA  DE EXEMPLO
CREATE TABLE FORNECEDORES
		(
		COD_FORNECEDOR NVARCHAR(5),
		NOME NVARCHAR(20)
		);

-- IMPORTANDO DADOS COM BULK INSERT
BULK INSERT FORNECEDORES
FROM 'C:\TEMP\BULK\FORNECEDORES.TXT'
WITH (
	 CODEPAGE = 'ACP',
	 DATAFILETYPE = 'CHAR',
	 FIELDTERMINATOR = '|',
	 ROWTERMINATOR = '\n',
	 MAXERRORS = 0,
	 FIRSTROW = 1,
	 LASTROW = 5
	 );

-- VERIFICANDO DADOS IMPORTADOS COM BULK INSERT
SELECT * FROM FORNECEDORES;