USE SALES;

-- CASE
-- AVALIA UMA LISTA DE CONDIÇÕES E RETORNA UMA DAS VÁRIAS EXPRESSÕES DE RESULTADO POSSÍVEIS. A EXPRESSÃO CASE POSSUI DOIS FORMATOS:
-- A EXPRESSÃO CASE SIMPLES COMPARA UMA EXPRESSÃO COM UM CONJUNTO DE EXPRESSÕES SIMPLES PARA DETERMINAR O RESULTADO.
-- A EXPRESSÃO CASE PESQUISADA AVALIA UM CONJUNTO DE EXPRESSÕES BOOLIANAS PARA DETERMINAR O RESULTADO.
-- OS DOIS FORMATOS DÃO SUPORTE A UM ARGUMENTO ELSE OPCIONAL.
-- PODE SER USADA COM INSTRUÇÕES, COMO SELECT, UPDATE, DELETE, SET, E EM CLÁUSULAS, COMO SELECT_LIST, IN, WHERE, ORDER BY E HAVING.

-- CASE (EXEMPLO 1)
SELECT A.ID_PROD, A.NOME_PRODUTO, B.NOME_CATEGORIA, A.PRECO,
	CASE
		WHEN A.PRECO < 500 THEN 'PRECO ABAIXO DE 500'
		WHEN A.PRECO >= 500 AND A.PRECO <=1000 THEN 'PRECO ENTRE 500 E 1000'
		WHEN A.PRECO > 1000 THEN 'PRECO ACIMA DE MIL'
	END AS FAIXA_PRECO
FROM   PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA=B.ID_CATEGORIA;

-- CASE (EXEMPLO 2)
DECLARE @DATA DATETIME;
SET @DATA = GETDATE() + 1;
SELECT @DATA,
	CASE
		WHEN @DATA = GETDATE() THEN 'HOJE'
		WHEN @DATA < GETDATE() THEN 'ONTEM'
		WHEN @DATA > GETDATE() THEN 'AMANHÃ'
		ELSE 'DIA NÃO ESPECIFICADO'
	END AS DIA;