-- NULLIF
-- RETORNA UM VALOR NULO SE AS DUAS EXPRESSÕES ESPECIFICADAS FOREM IGUAIS

-- NULLIF (EXEMPLO)
-- CRIANDO TABELA DE EXEMPLO
CREATE TABLE TESTE
		(
		 VALOR1 INT,
		 VALOR2 INT,
		 TEXTO VARCHAR(20)
		);
-- INSERINDO REGISTROS
INSERT INTO TESTE VALUES (100, 0, NULL), (100, 25, NULL), (1, 0, NULL), (5, 2, NULL);
-- VERIFICANDO REGISTROS
SELECT * FROM TESTE;
-- SIMULANDO ERRO
SELECT VALOR1,
	   VALOR2,
	   VALOR1/VALOR2 AS EXPRESSAO
FROM TESTE;
-- TRATANDO ERRO
SELECT VALOR1,
	   VALOR2,
	   ISNULL(VALOR1/NULLIF(VALOR2,0),0) AS RESULTADO1,
	   ISNULL(CAST(VALOR1 AS DECIMAL(5,2))/CAST(NULLIF(VALOR2,0) AS DECIMAL(5,2)),0) AS RESULTADO2
FROM TESTE;


-- ISNULL
-- SUBSTITUI NULL PELO VALOR DE SUBSTITUIÇÃO ESPECIFICADO

-- ISNULL (EXEMPLO)
SELECT VALOR1,
	   VALOR2,
	   ISNULL(TEXTO, 'VAZIO') AS TEXTO
FROM TESTE;