USE SALES;

-- UNION (UTILIZADO PARA COMBINAR O CONJUNTO DE RESULTADOS DE DUAS OU MAIS CONSULTAS)
SELECT 1, 10
	UNION
SELECT 5, 50;


SELECT NOME_PRODUTO, ID_CATEGORIA
FROM PRODUTOS
WHERE ID_CATEGORIA = 1
	UNION
SELECT NOME_PRODUTO, ID_CATEGORIA
FROM PRODUTOS
WHERE ID_CATEGORIA = 2;


-- UNION ALL (UTILIZADO PARA COMBINAR O CONJUNTO DE RESULTADOS DE DUAS OU MAIS CONSULTAS, PERMITINDO VALORES DUPLICADOS)
SELECT 1, 10
	UNION ALL
SELECT 1, 10;


SELECT NOME_CIDADE, UF
FROM CIDADE
WHERE NOME_CIDADE = 'NITERÓI' AND UF = 'RJ'
	UNION ALL
SELECT NOME_CIDADE, UF
FROM CIDADE
WHERE UF = 'RJ';
