USE SALES;

-- LINKED SERVER
-- O LINKED SERVER É UMA FUNCIONALIDADE DO SQL SERVER MUITO ÚTIL PARA ESTABELECER CONEXÃO SEGURA ENTRE DOIS OU MAIS SERVIDORES.
-- ESSA COMUNICAÇÃO É POSSÍVEL ENTRE FONTES OLE DB, COMO EXCEL, ACCESS, SERVIDORES SQL SERVER E ATÉ SERVIDORES COM OUTROS SGBDS COMO ORACLE.
-- AS PRINCIPAIS VANTAGENS DE SE UTILIZAR LINKED SERVER É A FACILIDADE DE EXECUTAR CONSULTAS DISTRIBUÍDAS, COMANDOS DE ATUALIZAÇÕES QUE ENVOLVEM DIVERSAS BASES EM SERVIDORES DIFERENTES.

-- OPENQUERY
-- EXECUTA A CONSULTA PASSAGEM ESPECIFICADA NO SERVIDOR VINCULADO ESPECIFICADO. ESSE SERVIDOR É UMA FONTE DE DADOS OLE DB.
-- OPENQUERY PODE SER REFERENCIADA NA CLÁUSULA FROM DE UMA CONSULTA COMO SE FOSSE UM NOME DE TABELA.
-- OPENQUERY TAMBÉM PODE SER REFERENCIADA COMO A TABELA DE DESTINO DE UMA INSTRUÇÃO INSERT, UPDATE OU DELETE. ISSO DEPENDERÁ DOS RECURSOS DO PROVEDOR OLE DB.
-- EMBORA A CONSULTA POSSA RETORNAR VÁRIOS CONJUNTOS DE RESULTADOS, OPENQUERY RETORNA SOMENTE O PRIMEIRO DELES.

-- EXEMPLO
-- VERIFICANDO SE EXISTE LINKED SERVER
SELECT * FROM SYS.SERVERS;

-- CRIANDO LINKED SERVER
EXEC	SP_ADDLINKEDSERVER
		@SERVER = 'LINKED_SERVER_1',
		@SRVPRODUCT = '',
		@PROVIDER = 'SQLNCLI',
		@DATASRC = 'FELIPEBACELO\SQLEXPRESS';

-- CRIANDO USUÁRIO DO LINKED SERVER
EXEC	SP_ADDLINKEDSRVLOGIN
		@RMTSRVNAME = 'LINKED_SERVER_1',
		@USESELF = 'TRUE',
		@LOCALLOGIN = 'FELIPEBACELO\FELIPE',
		@RMTUSER = NULL,
		@RMTPASSWORD = 'FELIPE123';

-- EXCLUINDO USUÁRIO DO LINKED SERVER
EXEC SP_DROPLINKEDSRVLOGIN @RMTSRVNAME = 'LINKED_SERVER_1', @LOCALLOGIN = 'FELIPEBACELO\FELIPE';

-- EXCLUINDO LINKED SERVER
EXEC SP_DROPSERVER @SERVER = 'LINKED_SERVER_1', @DROPLOGINS = 'DROPLOGINS';


-- OPENQUERY (SELECT)
SELECT * FROM OPENQUERY (LINKED_SERVER_1, 'SELECT * FROM SALES.DBO.ESTOQUE');

-- OPENQUERY (INSERT)
INSERT OPENQUERY (LINKED_SERVER_1, 'SELECT ID_PROD, NOME_PRODUTO, PRECO FROM SALES.DBO.ESTOQUE')
VALUES (20, 'IMPRESSORA', 750);

-- OPENQUERY (UPDATE)
UPDATE OPENQUERY (LINKED_SERVER_1, 'SELECT ID_PROD, NOME_PRODUTO, PRECO FROM SALES.DBO.ESTOQUE WHERE ID_PROD = 20')
SET PRECO = 850;

-- OPENQUERY (DELETE)
DELETE OPENQUERY (LINKED_SERVER_1, 'SELECT ID_PROD FROM SALES.DBO.ESTOQUE WHERE ID_PROD = ''20''');