USE SALES;

-- MERGE
-- UTILIZADO PARA REALIZAR OPERAÇÕES DE INSERT, UPDATE OU DELETE EM UMA TABELA DE DESTINO COM BASE NOS RESULTADOS DA JUNÇÃO COM A TABELA DE ORIGEM.

-- EXEMPLO 1
-- CRIANDO TABELA TEMPORÁRIA DE EXEMPLO #TAB1
CREATE TABLE #TAB1
		(
		NOME VARCHAR(50),
		CADASTRO DATETIME,
		ALTERACAO DATETIME,
		SITUACAO BIT
		);
-- INSERINDO REGISTROS NA TABELA #TAB1
INSERT #TAB1 VALUES
('ARTHUR', GETDATE(), NULL, 1),
('FELIPE', GETDATE(), NULL, 1),
('MALCON', GETDATE(), NULL, 1),
('THAISA', GETDATE(), NULL, 1),
('VICTOR', GETDATE(), NULL, 1);

-- CRIANDO TABELA TEMPORÁRIA DE EXEMPLO #TAB2
CREATE TABLE #TAB2
		(
		NOME VARCHAR(50),
		EMAIL VARCHAR(50)
		);
-- INSERINDO REGISTROS NA TABELA #TAB2
INSERT #TAB2 VALUES
('ARTHUR', 'ARTHUR@EMAIL.COM'),
('FELIPE', 'FELIPE@EMAIL.COM'),
('MALCON', 'MALCON@EMAIL.COM'),
('THAISA', 'THAISA@EMAIL.COM'),
('PETTER', 'PETTER@EMAIL.COM');

-- VERIFICANDO REGISTROS INSERIDOS NAS TABELAS
SELECT * FROM #TAB1;
SELECT * FROM #TAB2;

-- INICIANDO MERGE
MERGE #TAB1 AS DESTINO
USING #TAB2 AS ORIGEM
ON DESTINO.NOME = ORIGEM.NOME
-- QUANDO HÁ REGISTRO NO DESTINO E NA ORIGEM
WHEN MATCHED
THEN UPDATE SET SITUACAO = 0, ALTERACAO = GETDATE()
-- QUANDO NÃO HÁ REGISTRO NO DESTINO E HÁ NA ORIGEM
WHEN NOT MATCHED
THEN INSERT (NOME, CADASTRO, ALTERACAO, SITUACAO)
VALUES (ORIGEM.NOME, GETDATE(), GETDATE(), 1)
-- QUANDO HÁ REGISTRO NO DESTINO MAS NÃO HÁ NA ORIGEM
WHEN NOT MATCHED BY SOURCE
THEN UPDATE SET SITUACAO = NULL, ALTERACAO = GETDATE();
--VERIFICANDO RESULTADO
SELECT * FROM #TAB1;
SELECT * FROM #TAB2;


-- EXEMPLO 2
-- CRIANDO TABELA TEMPORÁRIA DE EXEMPLO #MERCEARIA
CREATE TABLE #MERCEARIA
		(
		COD_PRODUTO INT PRIMARY KEY,
		DESCRICAO VARCHAR(20),
		PRECO MONEY
		);
-- INSERINDO REGISTROS NA TABELA #MERCEARIA
INSERT #MERCEARIA VALUES
(1, 'CHÁ', 10.00),
(2, 'PÃO', 10.00),
(3, 'CAFÉ', 15.00),
(4, 'LEITE', 20.00),
(6, 'AÇÚCAR', 25.00);

-- CRIANDO TABELA TEMPORÁRIA DE EXEMPLO #MERCEARIA_ATUALIZADA
CREATE TABLE #MERCEARIA_ATUALIZADA
		(
		COD_PRODUTO INT PRIMARY KEY,
		DESCRICAO VARCHAR(20),
		PRECO MONEY
		);
-- INSERINDO REGISTROS NA TABELA #MERCEARIA_ATUALIZADA
INSERT #MERCEARIA_ATUALIZADA VALUES
(1, 'CHÁ', 10.00),
(2, 'PÃO', 15.00),
(3, 'CAFÉ', 20.00),
(6, 'PEIXE', 50.00);

-- VERIFICANDO REGISTROS INSERIDOS NAS TABELAS
SELECT * FROM #MERCEARIA;
SELECT * FROM #MERCEARIA_ATUALIZADA;

-- INICIANDO MERGE
MERGE #MERCEARIA AS DESTINO
USING #MERCEARIA_ATUALIZADA AS ORIGEM
ON DESTINO.COD_PRODUTO = ORIGEM.COD_PRODUTO
-- QUANDO HÁ REGISTRO NO DESTINO E NA ORIGEM
WHEN MATCHED AND DESTINO.DESCRICAO <> ORIGEM.DESCRICAO
OR DESTINO.PRECO <> ORIGEM.PRECO
THEN UPDATE SET DESTINO.DESCRICAO = ORIGEM.DESCRICAO,
				DESTINO.PRECO = ORIGEM.PRECO
-- QUANDO NÃO HÁ REGISTRO NO DESTINO E HÁ NA ORIGEM
WHEN NOT MATCHED BY TARGET
THEN INSERT (COD_PRODUTO, DESCRICAO, PRECO)
VALUES (ORIGEM.COD_PRODUTO, ORIGEM.DESCRICAO, ORIGEM.PRECO)
-- QUANDO HÁ REGISTRO NO DESTINO MAS NÃO HÁ NA ORIGEM
WHEN NOT MATCHED BY SOURCE
THEN DELETE
-- OUTPUT RETORNA INFORMAÇÕES OU EXPRESSÕES BASEADAS EM CADA LINHA AFETADA POR UMA INSTRUÇÃO INSERT, UPDATE, DELETE OU MERGE
-- $ACTION PARA ESPECIFICAR COLUNA 
OUTPUT $ACTION,
DELETED.COD_PRODUTO AS DESTINO_COD_PRODUTO,
DELETED.DESCRICAO AS DESTINO_DESCRICAO,
DELETED.PRECO AS DESTINO_PRECO,
INSERTED.COD_PRODUTO AS ORIGEM_COD_PRODUTO,
INSERTED.DESCRICAO AS ORIGEM_DESCRICAO,
INSERTED.PRECO AS ORIGEM_PRECO;

SELECT @@ROWCOUNT;

--VERIFICANDO RESULTADO
SELECT * FROM #MERCEARIA;
SELECT * FROM #MERCEARIA_ATUALIZADA;