USE SALES;

-- FUNÇÕES COM VALORES DE TABELA (MULTI-STATEMENT TABLE-VALUED FUNCTION)
-- AS FUNÇÕES COM VALOR DE TABELA DEFINIDAS PELO USUÁRIO RETORNAM UM TIPO DE DADO TABLE.
-- PARA UMA FUNÇÃO COM VALOR DE TABELA EMBUTIDA, NÃO HÁ UM CORPO DE FUNÇÃO, A TABELA É O CONJUNTO DE RESULTADOS DE UMA ÚNICA INSTRUÇÃO SELECT.

-- EXEMPLO 1
-- CRIANDO FUNÇÃO
CREATE FUNCTION FN_DESCRITOR(@CATEGORIA INT)
	RETURNS TABLE AS
		RETURN(
			SELECT A.ID_CATEGORIA,
				   A.NOME_PRODUTO,
				   A.PRECO,
				   B.NOME_CATEGORIA
			FROM PRODUTOS AS A
			INNER JOIN CATEGORIA AS B
			ON A.ID_CATEGORIA = B.ID_CATEGORIA
			WHERE A.ID_CATEGORIA = @CATEGORIA);
-- CHAMANDO FUNÇÃO
SELECT * FROM DBO.FN_DESCRITOR(2);
-- APAGANDO FUNÇÃO
DROP FUNCTION DBO.FN_DESCRITOR;

-- EXEMPLO 2
-- CRIANDO FUNÇÃO
CREATE FUNCTION FN_DIAS(@INTERVALO INT, @INICIO DATETIME, @FINAL DATETIME)
	RETURNS @TBL TABLE(SEQ INT, DT DATETIME) AS
		BEGIN
			DECLARE @CONT INT;
			SET @CONT = 1;
				WHILE @INICIO <= @FINAL
					BEGIN
						INSERT INTO @TBL(SEQ, DT) VALUES (@CONT, @INICIO)
							SET @INICIO = DATEADD(DAY, @INTERVALO, @INICIO)
							SET @CONT = @CONT + 1
					END
					RETURN
		END;
-- CHAMANDO FUNÇÃO
SELECT * FROM DBO.FN_DIAS(2, GETDATE(), GETDATE() + 15);
-- APAGANDO FUNÇÃO
DROP FUNCTION DBO.FN_DIAS;