USE SALES;

-- FUNÇÕES ESCALARES (SCALAR-VALUED USER DEFINED FUNCTION)
-- AS FUNÇÕES ESCALARES DEFINIDAS PELO USUÁRIO RETORNAM UM VALOR ÚNICO DE DADO DO TIPO DEFINIDO NA CLÁUSULA RETURNS.
-- PARA UMA FUNÇÃO ESCALAR EMBUTIDA, NÃO HÁ UM CORPO DE FUNÇÃO, O VALOR ESCALAR É O RESULTADO DE UMA ÚNICA INSTRUÇÃO.
-- PARA UMA FUNÇÃO ESCALAR DE VÁRIAS INSTRUÇÕES, O CORPO DA FUNÇÃO, DEFINIDO EM UM BLOCO BEGIN...END, CONTÉM UMA SÉRIE DE INSTRUÇÕES TSQL, QUE RETORNAM O VALOR ÚNICO.
-- O TIPO DE RETORNO PODE SER QUALQUER TIPO DE DADO, EXCETO TEXT, NTEXT, IMAGE, CURSOR E TIMESTAMP.

-- EXEMPLO 1
-- CRIANDO FUNÇÃO
CREATE FUNCTION FN_TRIM(@STRING VARCHAR(200))
	RETURNS VARCHAR(200)
		BEGIN
			RETURN(LTRIM(RTRIM(@STRING)))
		END;
-- CHAMANDO FUNÇÃO
SELECT '>' + ('     SQL     ') + '<'
UNION
SELECT '>' + DBO.FN_TRIM('     SQL     ') + '<';
-- ALTERANDO FUNÇÃO
ALTER FUNCTION FN_TRIM(@STRING VARCHAR(400))
	RETURNS VARCHAR(400)
		BEGIN
			RETURN(LTRIM(RTRIM(@STRING)))
		END;
-- APAGANDO FUNÇÃO
DROP FUNCTION FN_TRIM;


-- EXEMPLO 2
-- CRIANDO FUNÇÃO
CREATE FUNCTION FN_SUM(@NUM1 INT, @NUM2 INT)
	RETURNS INT
		BEGIN
			DECLARE @RESULTADO INT
			SET @RESULTADO = @NUM1 + @NUM2
			RETURN(@RESULTADO)
		END;
-- CHAMANDO FUNÇÃO
SELECT 'O RESULTADO É:', DBO.FN_SUM(10,40);
-- CRIANDO TABELA
CREATE TABLE #TESTE_SUM
		(
		VALOR1 INT,
		VALOR2 INT
		);
-- INSERINDO VALORES
INSERT INTO #TESTE_SUM VALUES (1, 10), (2, 10), (3, 10);
-- CHAMANDO FUNÇÃO
SELECT VALOR1,
	   VALOR2,
	   DBO.FN_SUM(VALOR1, VALOR2) AS RESULTADO
FROM #TESTE_SUM;
-- APAGANDO FUNÇÃO
DROP FUNCTION FN_SUM;