USE SALES;

-- FUNÇÕES EM LINHA (IN-LINE TABLE-VALUED FUNCTION)
-- AS FUNÇÕES EM LINHA DEFINIDAS PELO USUÁRIO SÃO MUITO UTILIZADAS PARA PARAMETRIZAR VIEWS.
-- O RETORNO DESTE TIPO DE FUNÇÃO É UM TIPO DE DADO TABLE, MAS COSTUMA-SE CRIAR O ESQUEMA EM MOMENTO DE EXECUÇÃO.
-- ESTE TIPO DE FUNÇÃO NÃO REQUER BEGIN...END NA CRIAÇÃO DO SEU CORPO.
-- PROPORCIONA MUITA PERFORMANCE QUANDO UTILIZADA EM VIEWS INDEXADAS.

-- EXEMPLO 1
-- CRIANDO FUNÇÃO
CREATE FUNCTION FN_QTD_PRODUTOS(@CATEGORIA VARCHAR(20))
	RETURNS TABLE AS
		RETURN
			(SELECT A.ID_CATEGORIA,
					A.NOME_PRODUTO,
					B.NOME_CATEGORIA
			 FROM PRODUTOS AS A
			 INNER JOIN CATEGORIA AS B
			 ON A.ID_CATEGORIA = B.ID_CATEGORIA
			 WHERE B.NOME_CATEGORIA = @CATEGORIA
			 GROUP BY B.NOME_CATEGORIA, A.NOME_PRODUTO, A.ID_CATEGORIA);
-- CHAMANDO FUNÇÃO
SELECT * FROM DBO.FN_QTD_PRODUTOS('INFORMÁTICA');
-- APAGANDO FUNÇÃO
DROP FUNCTION DBO.FN_QTD_PRODUTOS;