USE SALES;

-- IF
-- A ESTRUTURA CONDICIONAL IF SERÁ EXECUTADA SE A CONDIÇÃO FOR SATISFEITA: A EXPRESSÃO BOOLEANA RETORNA TRUE.
-- A PALAVRA-CHAVE OPCIONAL ELSE INTRODUZ OUTRA INSTRUÇÃO CONDIÇÃO QUE SERÁ EXECUTADA QUANDO A CONDIÇÃO IF NÃO FOR ATENDIDA: A EXPRESSÃO BOOLIANA RETORNA FALSE.

-- IF (EXEMPLO 1)
IF 10 = 10
	BEGIN
		PRINT 'CORRETO'
	END
	ELSE
		PRINT 'ERRADO';

-- IF (EXEMPLO 2)
IF 10 = 10 AND 20 <> 20
	BEGIN
		PRINT 'CORRETO'
	END
	ELSE
		PRINT 'ERRADO';

-- IF (EXEMPLO 3)
IF 10 = 10 AND 20 = 300
	BEGIN
		PRINT 'CORRETO'
	END
	ELSE
		PRINT 'ERRADO';

-- IF (EXEMPLO 4)
IF 10 <> 10 OR 20 = 20
	BEGIN
		PRINT 'CORRETO'
	END
	ELSE
		PRINT 'ERRADO';

-- IF (EXEMPLO 5)
DECLARE @IDADE INT;
SET @IDADE = 70;

IF @IDADE < 18
	PRINT 'POSSUI MENOS DE 18 ANOS';
ELSE IF @IDADE >= 18 AND @IDADE < 65
	PRINT 'POSSUI MAIS DE 18 ANOS';
ELSE
	PRINT 'POSSUI 65 ANOS OU MAIS';

-- IF (EXEMPLO 6)
DECLARE @ID_CATEGORIA INT;
SET @ID_CATEGORIA = '1';
IF (SELECT COUNT(*)
	FROM PRODUTOS
	WHERE ID_CATEGORIA = @ID_CATEGORIA) = 0
		BEGIN
			PRINT 'CATEGORIA NÃO ENCONTRADA'
		END
		ELSE
		BEGIN
			PRINT 'CATEGORIA ENCONTRADA';
			SELECT B.NOME_CATEGORIA, A.NOME_PRODUTO, A.PRECO
			FROM PRODUTOS AS A
			INNER JOIN CATEGORIA AS B
			ON A.ID_CATEGORIA = B.ID_CATEGORIA
			AND A.ID_CATEGORIA = @ID_CATEGORIA
		END;