USE SALES;

-- WHILE
-- DEFINE UMA CONDIÇÃO PARA A EXECUÇÃO REPETIDA DE UMA INSTRUÇÃO OU UM BLOCO DE INSTRUÇÕES SQL.
-- AS INSTRUÇÕES SERÃO EXECUTADAS REPETIDAMENTE DESDE QUE A CONDIÇÃO ESPECIFICADA SEJA VERDADEIRA.
-- A EXECUÇÃO DE INSTRUÇÕES NO LOOP WHILE PODE SER CONTROLADA INTERNAMENTE AO LOOP COM AS PALAVRAS-CHAVE BREAK E CONTINUE.

-- WHILE (EXEMPLO 1)
DECLARE @CONTADOR INT
SET @CONTADOR = 10
WHILE (SELECT GETDATE() - @CONTADOR) <= GETDATE()
	BEGIN
		PRINT GETDATE() - @CONTADOR
		SET @CONTADOR = @CONTADOR - 1
	IF (GETDATE() - @CONTADOR) >= GETDATE()
		BREAK
	ELSE
		CONTINUE
	END;

-- WHILE (EXEMPLO 2)
DECLARE @CONT INT,
		@TAB INT
SET @CONT = 0
SET @TAB = 9
WHILE (@CONT <= 10)
	BEGIN
		PRINT CAST(@CONT AS NVARCHAR) + N' X ' + CAST(@TAB AS NVARCHAR) + N' = ' + CAST(@CONT * @TAB AS NVARCHAR)
		SET @CONT = @CONT + 1
	END;

-- WHILE (EXEMPLO 3)
DECLARE @VALOR1 INT,
		@VALOR2 INT,
		@MOD INT
SET @VALOR1 = 1
SET @VALOR2 = 10
WHILE(@VALOR1 <= @VALOR2)
	BEGIN
		SET @MOD = @VALOR1%2
		IF @MOD = 0
 			BEGIN
				PRINT 'O NÚMERO ' + CAST(@VALOR1 AS NCHAR(2)) + ' É PAR'
				SET @VALOR1 = @VALOR1 + 1
			END
		ELSE
			BEGIN
				PRINT 'O NÚMERO ' + CAST(@VALOR1 AS NCHAR(2)) + ' É ÍMPAR'
				SET @VALOR1 = @VALOR1 + 1
			END
	END;