USE SALES;

-- UTILIZANDO OPERADOR =
SELECT * FROM CIDADE
WHERE UF = 'SP';

SELECT * FROM CIDADE
WHERE NOME_CIDADE = 'Campinas';

SELECT * FROM CIDADE
WHERE UF = 'SP' AND NOME_CIDADE = 'Campinas';

-- UTILIZANDO OPERADOR >
SELECT * FROM CIDADE
WHERE ID_CIDADE > 3;

-- UTILIZANDO OPERADOR <
SELECT * FROM CIDADE
WHERE ID_CIDADE < 3;

-- UTILIZANDO OPERADOR >=
SELECT * FROM CIDADE
WHERE ID_CIDADE >= 4;

-- UTILIZANDO OPERADOR <=
SELECT * FROM CIDADE
WHERE ID_CIDADE <= 3;

-- UTILIZANDO OPERADOR <>
SELECT * FROM CIDADE
WHERE UF <> 'SP' AND NOME_CIDADE <> 'Niterói';

-- COMBINANDO OPERADORES
SELECT * FROM CIDADE
WHERE UF = 'RJ' AND NOME_CIDADE <> 'Niterói' AND ID_CIDADE = 1;

SELECT * FROM CIDADE
WHERE ID_CIDADE >= 4 AND NOME_CIDADE <> 'São Paulo';