USE SALES;

-- OPERADOR WHERE
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO = 'TECLADO';

-- OPERADOR AND
SELECT * FROM PRODUTOS
WHERE ID_CATEGORIA = 1 AND PRECO >= 700;

-- OPERADOR BETWEEN
SELECT ID_PROD, NOME_PRODUTO, PRECO
FROM PRODUTOS
WHERE PRECO BETWEEN 350 AND 750;

SELECT * FROM VENDAS
WHERE ID_VENDEDOR = 6
AND VALOR_TOTAL BETWEEN 50000 AND 60000;

SELECT * FROM VENDAS
WHERE ID_VENDEDOR = 6
AND DATA_VENDA BETWEEN '2017-03-01' AND '2017-03-31';

-- OPERADOR IN
SELECT * FROM VENDAS
WHERE NUM_VENDA IN ('30','60','90');

-- OPERADOR NOT IN
SELECT * FROM VENDAS
WHERE NUM_VENDA NOT IN ('30','60','90')
AND ID_CLIENTE IN ('2');

-- OPERADOR LIKE (RETORNA REGISTROS QUE CONTENHAM 'OR' EM QUALQUER POSIÇÃO)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE '%OR%';

-- OPERADOR LIKE (RETORNA REGISTROS QUE CONTENHAM 'S' NA SEGUNDA POSIÇÃO)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE '_S%';

-- OPERADOR LIKE (RETORNA REGISTROS QUE CONTENHAM 'A' NA PRIMEIRA POSIÇÃO)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE 'A%';

-- OPERADOR LIKE (RETORNA REGISTROS QUE CONTENHAM 'M' NA PRIMEIRA POSIÇÃO E AO MENOS 6 CARACTERES)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE 'M_%_%_%_%_%';

-- OPERADOR LIKE (RETORNA REGISTROS QUE CONTENHAM 'F' NA PRIMEIRA POSIÇÃO E 'O' NA ÚLTIMA POSIÇÃO)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE 'F%O';

-- OPERADOR NOT LIKE (RETORNA REGISTROS QUE NÃO CONTENHAM 'A' NA PRIMEIRA POSIÇÃO)
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO NOT LIKE 'A%';

-- OPERADOR LIKE [] (RETORNA REGISTROS QUE CONTENHAM 'F' OU 'P' NA PRIMEIRA POSIÇÃO E E NA SEQUÊNCIA 'E')
SELECT * FROM VENDEDORES
WHERE NOME_VENDEDOR LIKE '[FP]E%';

-- OPERADOR LIKE [] (RETORNA REGISTROS QUE CONTENHAM 'GRA' NA PRIMEIRA POSIÇÃO E NA SEQUÊNCIA 'C' OU 'Z')
SELECT * FROM VENDEDORES
WHERE NOME_VENDEDOR LIKE 'GRA[CZ]%';

-- OPERADOR LIKE [] (RETORNA REGISTROS QUE CONTENHAM 'LUI' NA PRIMEIRA POSIÇÃO E NA SEQUÊNCIA 'Z' OU 'S')
SELECT * FROM VENDEDORES
WHERE NOME_VENDEDOR LIKE 'LUI[ZS]%';

-- OPERADOR NOT
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE 'T%'
AND NOT PRECO > 1000;

-- OPERADOR OR
SELECT * FROM PRODUTOS
WHERE PRECO < 1000
AND (ID_CATEGORIA = 1 OR ID_CATEGORIA = 2);

-- OPERADOR IS NULL
SELECT * FROM PRODUTOS
WHERE ID_PROD IS NULL;

-- OPERADOR IS NOT NULL
SELECT * FROM PRODUTOS
WHERE ID_PROD IS NOT NULL;

-- OPERADOR EXISTS
SELECT A.NOME_PRODUTO, A.ID_CATEGORIA
FROM PRODUTOS AS A
WHERE EXISTS
	(SELECT * FROM CATEGORIA AS B
	 WHERE A.ID_CATEGORIA = B.ID_CATEGORIA
	 AND A.NOME_PRODUTO = 'TECLADO');

-- OPERADOR ANY
SELECT DISTINCT A.ID_CATEGORIA
FROM CATEGORIA AS A
WHERE A.ID_CATEGORIA = ANY
	(SELECT B.ID_CATEGORIA
	 FROM PRODUTOS AS B);

-- OPERADOR HAVING
SELECT A.UF,
	   COUNT(A.ID_CIDADE) AS QTD_CIDADES
	   FROM CIDADE AS A
	   GROUP BY A.UF HAVING COUNT(A.ID_CIDADE) > 2
	   ORDER BY 2 DESC;

SELECT A.ID_VENDEDOR,
	   SUM(A.VALOR_TOTAL) AS TOTAL_VENDAS
	   FROM VENDAS AS A
	   GROUP BY A.ID_VENDEDOR HAVING SUM(A.VALOR_TOTAL) >= 2000000
	   ORDER BY 2 DESC;