-- OPERADOR DE ADIÇÃO
SELECT 5 + 5 AS RESULTADO;

-- OPERADOR DE SUBTRAÇÃO
SELECT 5 - 3 AS RESULTADO;

-- OPERADOR DE MULTIPLICAÇÃO
SELECT 5 * 5 AS RESULTADO;

-- OPERADOR DE DIVISÃO
SELECT 50 / 5 AS RESULTADO;

-- OPERADOR DE MÓDULO (RETORNA O RESTO DA DIVISÃO)
SELECT 12 % 5 AS RESULTADO;

-- EXEMPLOS DE OPERAÇÕES
SELECT ((10+5)*(5-3))/3 AS RESULTADO;
SELECT ((50+5)/(6-1))+4 AS RESULTADO;
SELECT ((10*5)*(7-6))+1 AS RESULTADO;
SELECT ((50+5)/(8-7))-4 AS RESULTADO;