-- PRINCIPAIS COMBINAÇÕES PARA FORMATAÇÃO DE DATAS 

SELECT CONVERT(VARCHAR(10), GETDATE(), 103);

SELECT CONVERT(VARCHAR(5), GETDATE(), 103);

SELECT CONVERT(VARCHAR(10), GETDATE(), 108);

SELECT CONVERT(VARCHAR(5), GETDATE(), 108);

SELECT CONVERT(VARCHAR(20), GETDATE(), 100);

SELECT CONVERT(VARCHAR(8), GETDATE(), 1);

SELECT CONVERT(VARCHAR(10), GETDATE(), 103),
	   SUBSTRING(CONVERT(VARCHAR(10), GETDATE(), 103), 4, 2);

SELECT CAST(DAY(GETDATE()) AS VARCHAR(2)) + ' de ' +
	   DATENAME(MM, GETDATE()) AS [DIA E MES];