-- ASCII (RETORNA O VALOR DO CÓDIGO ASCII DO CARACTERE MAIS À ESQUERDA DE UMA EXPRESSÃO DE CARACTERE)
-- ASCII (EXEMPLO)
SELECT ASCII('EXEMPLO');
SELECT ASCII('E');

-- LTRIM (RETORNA UMA EXPRESSÃO DE CARACTERE DEPOIS DE REMOVER ESPAÇOS EM BRANCO À ESQUERDA)
-- LTRIM (EXEMPLO)
SELECT LTRIM('   EXEMPLO');

-- RTRIM (RETORNA UMA CADEIA DE CARACTERES DEPOIS DE TRUNCAR TODOS OS ESPAÇOS À DIREITA)
-- RTRIM (EXEMPLO)
SELECT RTRIM('EXEMPLO   ');

-- STR (RETORNA DADOS DE CARACTERE CONVERTIDOS DE DADOS NUMÉRICOS)
-- O PRIMEIRO ARGUMENTO É A EXPRESSÃO DE TIPO DE DADOS NUMÉRICO APROXIMADO (FLOAT) COM UM SEPARADOR DECIMAL
-- O SEGUNDO ARGUMENTO É O COMPRIMENTO TOTAL, INCLUINDO O PONTO DECIMAL, SINAL, DÍGITOS E ESPAÇOS
-- O TERCEIRO ARGUMENTO É O NÚMERO DE DÍGITOS À DIREITA DA VÍRGULA DECIMAL
-- STR (EXEMPLO)
SELECT STR(155.50, 6, 2);
SELECT 'EXEMPLO '+ STR(155.50, 6, 2);

-- SUBSTRING (RETORNA UMA SUBSTRING DE CARACTERE COM DADOS DE CARACTERE DENTRO DO PARÂMETRO INFORMADO)
-- SUBSTRING (EXEMPLO)
DECLARE @NOME VARCHAR(14);
SET @NOME = 'BANCO DE DADOS';
	SELECT @NOME,
	SUBSTRING(@NOME, 1, 5) AS POSICAO1A5,
	SUBSTRING(@NOME, 10, 14) AS POSICAO10A14;

-- CONCAT (RETORNA UMA CADEIA DE CARACTERES RESULTANTE DE CONCATENAÇÃO OU JUNÇÃO DE DOIS OU MAIS VALORES)
-- CONCAT (EXEMPLO)
SELECT CONCAT('HAPPY ', 'BIRTHDAY');
SELECT CONCAT('HAPPY ', 'BIRTHDAY ', '01', '/', '03');

-- CONCAT_WS (SEPARA E RETORNA VALORES DE CADEIA DE CARACTERES CONCATENADOS COM O DELIMITADOR ESPECIFICADO NO ARGUMENTO DA PRIMEIRA FUNÇÃO)
-- CONCAT_WS (EXEMPLO)
SELECT CONCAT_WS('|', 'T', 'E', 'S', 'T', 'E');
SELECT CONCAT_WS('-', 'T', 'E', 'S', 'T', 'E');
SELECT CONCAT_WS(';', 'T', 'E', 'S', 'T', 'E');

-- REPLACE (SUBSTITUI TODAS AS OCORRÊNCIAS DE UM VALOR DA CADEIA DE CARACTERES ESPECIFICADO POR OUTRO VALOR DE CADEIA DE CARACTERES)
-- REPLACE (EXEMPLO)
SELECT REPLACE('ABCDEF', 'CD', 'XX');

-- REPLICATE (REPETE UM VALOR DA CADEIA DE CARACTERES UM NÚMERO ESPECIFICADO DE VEZES)
-- REPLICATE (EXEMPLO)
SELECT REPLICATE('SQL ', 5);

-- LEFT (RETORNA A PARTE DA ESQUERDA DE UMA CADEIA DE CARACTERES COM O NÚMERO DE CARACTERES ESPECIFICADO)
-- LEFT (EXEMPLO)
SELECT LEFT('EXEMPLO', 3);

-- RIGHT (RETORNA A PARTE DA DIREITA DE UMA CADEIA DE CARACTERES COM O NÚMERO DE CARACTERES ESPECIFICADO)
-- RIGHT (EXEMPLO)
SELECT RIGHT('EXEMPLO', 3);

-- UPPER (RETORNA UMA EXPRESSÃO DE CARACTERE COM DADOS DE CARACTERE EM MINÚSCULAS CONVERTIDOS EM MAIÚSCULAS)
-- UPPER (EXEMPLO)
SELECT UPPER('Teste');

-- LOWER (RETORNA UMA EXPRESSÃO DE CARACTERE DEPOIS DE CONVERTER PARA MINÚSCULAS OS DADOS DE CARACTERES EM MAIÚSCULAS)
-- LOWER (EXEMPLO)
SELECT LOWER('Teste');

-- REVERSE (RETORNA A ORDEM INVERSA DE UM VALOR DA CADEIA DE CARACTERES)
-- REVERSE (EXEMPLO)
SELECT REVERSE('EXEMPLO');

-- LEN (RETORNA O NÚMERO DE CARACTERES DA EXPRESSÃO DE CADEIA DE CARACTERES ESPECIFICADA, EXCLUINDO ESPAÇOS À DIREITA)
-- LEN (EXEMPLO)
SELECT LEN('EXEMPLO');
SELECT LEN('EXEMPLO   ');
SELECT LEN('   EXEMPLO');

-- DATALENGTH (RETORNA O NÚMERO DE BYTES USADO PARA REPRESENTAR QUALQUER EXPRESSÃO)
-- DATALENGTH (EXEMPLO)
SELECT DATALENGTH('EXEMPLO');
SELECT DATALENGTH('EXEMPLO   ');
SELECT DATALENGTH('   EXEMPLO');