USE SALES;

-- CHOOSE
-- RETORNA O ITEM AO ÍNDICE ESPECIFICADO DE UMA LISTA DE VALORES.

-- CHOOSE (EXEMPLO 1)
SELECT CHOOSE (3, 'X-BURGUER', 'X-SALADA', 'X-BACON', 'X-EGG', '') AS LANCHE_ESCOLHIDO;

-- CHOOSE (EXEMPLO 2)
SELECT ID_PROD, NOME_PRODUTO, ID_CATEGORIA,
CHOOSE (ID_CATEGORIA, 'A', 'B', 'C', 'D', 'E') AS COD_CATEGORIA
FROM PRODUTOS;


-- IIF
-- RETORNA UM DE DOIS VALORES, DEPENDENDO DA EXPRESSÃO BOOLEANA SER AVALIADA COMO TRUE OU FALSE.

-- IIF (EXEMPLO 1)
DECLARE @A INT = 55, @B INT = 50;
	SELECT IIF (@A > @B, 'TRUE', 'FALSE') AS RESULTADO;

-- IIF (EXEMPLO 2)
DECLARE @C INT = 55, @D INT = 50;
	SELECT IIF (@C > @D, 'MAIOR', 'MENOR') AS RESULTADO;