USE SALES;

-- AVG (RETORNA A MÉDIA DOS VALORES EM UM GRUPO. VALORES NULOS SÃO IGNORADOS)
-- AVG (EXEMPLO 1)
SELECT AVG(PRECO) FROM PRODUTOS;

-- AVG (EXEMPLO 2)
SELECT ID_CATEGORIA, AVG(PRECO) AS MEDIA
	FROM PRODUTOS
GROUP BY ID_CATEGORIA
ORDER BY MEDIA DESC;

-- AVG (EXEMPLO 3)
SELECT B.NOME_CATEGORIA, AVG(A.PRECO)
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- MIN (RETORNA O VALOR MÍNIMO NA EXPRESSÃO. PODE SER SEGUIDO PELA CLÁUSULA OVER)
-- MIN (EXEMPLO 1)
SELECT MIN(PRECO) FROM PRODUTOS;

-- MIN (EXEMPLO 2)
SELECT ID_CATEGORIA, MIN(PRECO) AS MEDIA
	FROM PRODUTOS
GROUP BY ID_CATEGORIA
ORDER BY MEDIA DESC;

-- MIN (EXEMPLO 3)
SELECT B.NOME_CATEGORIA, MIN(A.PRECO)
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- MAX (RETORNA O VALOR MÁXIMO NA EXPRESSÃO)
-- MAX (EXEMPLO 1)
SELECT MAX(PRECO) FROM PRODUTOS;

-- MAX (EXEMPLO 2)
SELECT ID_CATEGORIA, MAX(PRECO) AS MEDIA
	FROM PRODUTOS
GROUP BY ID_CATEGORIA
ORDER BY MEDIA DESC;

-- MAX (EXEMPLO 3)
SELECT B.NOME_CATEGORIA, MAX(A.PRECO)
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- SUM (RETORNA A SOMA DE TODOS OS VALORES OU SOMENTE OS VALORES DISTINCT NA EXPRESSÃO. VALORES NULOS SÃO IGNORADOS)
-- SUM (EXEMPLO 1)
SELECT SUM(PRECO) FROM PRODUTOS;

-- SUM (EXEMPLO 2)
SELECT ID_CATEGORIA, SUM(PRECO) AS MEDIA
	FROM PRODUTOS
GROUP BY ID_CATEGORIA
ORDER BY MEDIA DESC;

-- SUM (EXEMPLO 3)
SELECT B.NOME_CATEGORIA, SUM(A.PRECO)
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- COUNT (RETORNA O NÚMERO DE REGISTROS DE UM GRUPO)
-- COUNT (EXEMPLO 1)
SELECT COUNT(DISTINCT PRECO) FROM PRODUTOS;

-- COUNT (EXEMPLO 2)
SELECT ID_CATEGORIA, COUNT(PRECO) AS MEDIA
	FROM PRODUTOS
GROUP BY ID_CATEGORIA
ORDER BY MEDIA DESC;

-- COUNT (EXEMPLO 3)
SELECT B.NOME_CATEGORIA, COUNT(A.PRECO)
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- STDEV (RETORNA O DESVIO PADRÃO ESTATÍSTICO DE TODOS OS VALORES DA EXPRESSÃO ESPECIFICADA)
-- STDEV (EXEMPLO)
SELECT STDEV(PRECO) FROM PRODUTOS;

-- STDEVP (RETORNA O DESVIO PADRÃO ESTATÍSTICO PARA A POPULAÇÃO DE TODOS OS VALORES NA EXPRESSÃO ESPECIFICADA)
-- STDEVP (EXEMPLO)
SELECT STDEV(PRECO) FROM PRODUTOS;

-- GROUPING (INDICA SE UMA EXPRESSÃO DE COLUNA ESPECIFICADA EM UMA LISTA GROUP BY. RETORNA 1 PARA AGREGADA E 0 PARA NÃO AGREGADA)
-- GROUPING (EXEMPLO)
SELECT ID_CATEGORIA, SUM(PRECO) AS TOTAL,
GROUPING(ID_CATEGORIA) AS GRUPO
	FROM PRODUTOS
GROUP BY ID_CATEGORIA WITH ROLLUP;

-- GROUPING_ID (CALCULA O NÍVEL DE AGRUPAMENTO. PODE SER USADA APENAS NA LISTA SELECT, NA CLÁUSULA HAVING OU ORDER BY, QUANDO GROUP BY FOR ESPECIFICADA)
-- GROUPING_ID (EXEMPLO)
SELECT A.ID_CATEGORIA, B.NOME_CATEGORIA, SUM(A.PRECO) AS TOTAL,
GROUPING_ID(A.ID_CATEGORIA, B.NOME_CATEGORIA) AS GRUPO
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY ROLLUP(A.ID_CATEGORIA, B.NOME_CATEGORIA);

-- VAR (RETORNA A VARIÂNCIA ESTATÍSTICA DE TODOS OS VALORES DA EXPRESSÃO ESPECIFICADA)
-- VAR (EXEMPLO 1)
SELECT VAR(PRECO) FROM PRODUTOS;

-- VAR (EXEMPLO 2)
SELECT B.NOME_CATEGORIA, VAR(A.PRECO) AS VAR
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- VARP (RETORNA A VARIÂNCIA ESTATÍSTICA PARA O PREENCHIMENTO DE TODOS OS VALORES DA EXPRESSÃO ESPECIFICADA)
-- VARP (EXEMPLO 1)
SELECT VARP(PRECO) FROM PRODUTOS;

-- VARP (EXEMPLO 2)
SELECT B.NOME_CATEGORIA, VARP(A.PRECO) AS VARP
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;

-- COMPARANDO VAR E VARP
SELECT B.NOME_CATEGORIA, VAR(A.PRECO) AS VAR, VARP(A.PRECO) AS VARP
	FROM PRODUTOS AS A
INNER JOIN CATEGORIA AS B
ON A.ID_CATEGORIA = B.ID_CATEGORIA
GROUP BY NOME_CATEGORIA
ORDER BY 2 DESC;