-- DATENAME (DATEPART, DATE)
-- RETORNA UMA CADEIA DE CARACTERES QUE REPRESENTA O DATEPART ESPECÍFICO DA DATA ESPECIFICADA
SELECT DATENAME(DAY, GETDATE()) DIA,
	   DATENAME(MONTH, GETDATE()) MES,
	   DATENAME(YEAR, GETDATE()) ANO;

-- DATEPART (DATEPART, DATE)
-- RETORNA UM INTEIRO QUE REPRESENTA A DATEPART ESPECIFICADA DA DATE ESPECIFICADA
SELECT DATEPART(DAY, GETDATE()) DIA,
	   DATEPART(MONTH, GETDATE()) MES,
	   DATEPART(YEAR, GETDATE()) ANO;

-- DAY (DATE)
-- RETORNA UM INTEIRO QUE REPRESENTA A PARTE DO DIA DA DATE ESPECIFICADA
SELECT DAY(GETDATE()) DIA;

-- MONTH (DATE)
-- RETORNA UM INTEIRO QUE REPRESENTA A PARTE DO MÊS DA DATE ESPECIFICADA
SELECT MONTH(GETDATE()) MES;

-- YEAR (DATE)
-- RETORNA UM INTEIRO QUE REPRESENTA A PARTE DO ANO DA DATE ESPECIFICADA
SELECT YEAR(GETDATE()) ANO;

-- DATETIMEFROMPARTS (YEAR, MONTH, DAY, HOUR, MINUTE, SECONDS, MILLISECONDS)
-- RETORNA UM VALOR DATETIME PARA A DATA E A HORA ESPECIFICADAS
SELECT DATETIMEFROMPARTS(2021,03,01,6,50,55,10) HORA;