USE SALES;

-- TOP (SELECIONANDO OS 5 PRIMEIROS REGISTROS)
SELECT TOP 5 * FROM PRODUTOS
ORDER BY ID_PROD ASC;

-- TOP (SELECIONANDO OS 5 ÚLTIMOS REGISTROS)
SELECT TOP 5 * FROM PRODUTOS
ORDER BY ID_PROD DESC;

-- TOP (SELECIONANDO OS 2 ÚLTIMOS REGISTROS)
SELECT TOP 2 A.NOME_PRODUTO, B.NOME_CATEGORIA
	FROM PRODUTOS AS A
	INNER JOIN CATEGORIA AS B
	ON A.ID_CATEGORIA=B.ID_CATEGORIA
ORDER BY B.NOME_CATEGORIA DESC;