-- SYSDATETIME
-- RETORNA UM VALOR DE DATETIME2(7) QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- O DESLOCAMENTO DE FUSO HORÁRIO NÃO ESTÁ INCLUÍDO
SELECT SYSDATETIME();

-- SYSDATETIMEOFFSET
-- RETORNA UM VALOR DATETIMEOFFSET(7) QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- O DESLOCAMENTO DE FUSO HORÁRIO ESTÁ INCLUÍDO
SELECT SYSDATETIMEOFFSET();

-- SYSUTCDATETIME
-- RETORNA UM VALOR DE DATETIME2(7) QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- A DATA E A HORA É RETORNADA COMO HORA UTC (TEMPO UNIVERSAL COORDENADO)
SELECT SYSUTCDATETIME();

-- CURRENT_TIMESTAMP
-- RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- O DESLOCAMENTO DE FUSO HORÁRIO NÃO ESTÁ INCLUÍDO
SELECT CURRENT_TIMESTAMP;

-- GETDATE
-- RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- O DESLOCAMENTO DE FUSO HORÁRIO NÃO ESTÁ INCLUÍDO
SELECT GETDATE();

-- GETUTCDATE
-- RETORNA UM VALOR DATETIME QUE CONTÉM A DATA E A HORA DO COMPUTADOR NO QUAL A INSTÂNCIA DO SQL SERVER ESTÁ SENDO EXECUTADA
-- A DATA E A HORA É RETORNADA COMO HORA UTC (TEMPO UNIVERSAL COORDENADO)
SELECT GETUTCDATE();


-- COMPARANDO EXEMPLOS
SELECT SYSDATETIME() AS ASYSDATETIME;
SELECT SYSDATETIMEOFFSET() AS ASYSDATETIMEOFFSET;
SELECT SYSUTCDATETIME() AS ASYSUTCDATETIME;
SELECT CURRENT_TIMESTAMP AS ACURRENT_TIMESTAMP;
SELECT GETDATE() AS AGETDATE;
SELECT GETUTCDATE() AS AGETUTCDATE;