USE SALES;

-- ABS (RETORNA O VALOR ABSOLUTO 'POSITIVO' DA EXPRESSÃO NUMÉRICA ESPECIFICADA)
-- ABS (EXEMPLO)
SELECT ABS(-5.5),
	   ABS(-9.5),
	   ABS(5.0),
	   ABS(9.5),
	   ABS(0.0);

-- CEILING (RETORNA O MENOR INTEIRO MAIOR QUE OU IGUAL A EXPRESSÃO NUMÉRICA ESPECIFICADA)
-- CEILING (EXEMPLO)
SELECT CEILING(51.55);
SELECT CEILING(25.25);

-- RAND (RETORNA UM VALOR FLOAT PSEUDOALEATÓRIO DE 0 A 1, EXCLUSIVO)
-- RAND (EXEMPLO)
SELECT RAND(),
	   RAND(),
	   RAND(),
	   RAND(),
	   RAND();

-- ROUND (RETORNA UM VALOR NUMÉRICO, ARREDONDANDO, PARA O COMPRIMENTO OU PRECISÃO ESPECIFICADOS)
-- ROUND (EXEMPLO)
SELECT ROUND(150.9994, 3),
	   ROUND(150.9995, 3),
	   ROUND(150.9994, 2),
	   ROUND(150.9995, 2),
	   ROUND(150.9994,-2),
	   ROUND(149.9995,-2);

-- POWER (RETORNA O VALOR DA EXPRESSÃO ESPECIFICADA PARA A POTÊNCIA INDICADA)
-- POWER (EXEMPLO)
SELECT POWER(3,2);
SELECT POWER(3,3);

-- SQRT (RETORNA A RAIZ QUADRADA DO VALOR FLUTUANTE ESPECIFICADO)
-- SQRT (EXEMPLO)
SELECT SQRT(25);
SELECT SQRT(36);
SELECT SQRT(50);
SELECT SQRT(64);
SELECT SQRT(81);

-- SQUARE (RETORNA O QUADRADO DO VALOR FLUTUANTE ESPECIFICADO)
-- SQUARE (EXEMPLO)
SELECT SQUARE(10);
SELECT SQUARE(11);
SELECT SQUARE(12);