USE SALES;

-- RANK
-- AS FUNÇÕES DE CLASSIFICAÇÃO RETORNAM UM VALOR DE CLASSIFICAÇÃO PARA CADA LINHA EM UMA PARTIÇÃO.
-- DEPENDENDO DA FUNÇÃO USADA, ALGUMAS LINHAS PODEM RECEBER O MESMO VALOR QUE OUTRAS.
-- AS FUNÇÕES DE CLASSIFICAÇÃO SÃO NÃO DETERMINÍSTICAS

-- RANK (EXEMPLO 1)
SELECT RANK() OVER (ORDER BY NOME_PRODUTO ASC) AS RANK_PRODUTO,
	NOME_PRODUTO
FROM PRODUTOS;

-- RANK (EXEMPLO 2)
SELECT RANK() OVER (ORDER BY NOME_PRODUTO ASC) AS RANK_PRODUTO,
	NOME_PRODUTO,
	ID_CATEGORIA
FROM PRODUTOS;

-- RANK (EXEMPLO 3)
SELECT RANK() OVER (ORDER BY ID_CATEGORIA ASC) AS RANK_CATEGORIA,
	ID_CATEGORIA,
	NOME_PRODUTO
FROM PRODUTOS;


-- NTILE
-- DISTRIBUI AS LINHAS DE UMA PARTIÇÃO ORDENADA EM UM NÚMERO DE GRUPOS ESPECIFICADO.
-- OS GRUPOS SÃO NUMERADOS, INICIANDO EM 1. PARA CADA LINHA.
-- NTILE RETORNA O NÚMERO DO GRUPO AO QUAL A LINHA PERTENCE.

-- NTILE (EXEMPLO)
SELECT NTILE(4) OVER (ORDER BY ID_CATEGORIA ASC) AS NTILE_CATEGORIA,
	ID_CATEGORIA,
	NOME_PRODUTO
FROM PRODUTOS;


-- DENSE_RANK
-- RETORNA A CLASSIFICAÇÃO DE LINHAS DENTRO DA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
-- SEM QUALQUER LACUNA NA CLASSIFICAÇÃO. A CLASSIFICAÇÃO DE UMA LINHA É 1 MAIS
-- O NÚMERO DE CLASSIFICAÇÕES DISTINTAS QUE VÊM ANTES DA LINHA EM QUESTÃO.

-- DENSE_RANK (EXEMPLO)
SELECT DENSE_RANK() OVER (ORDER BY ID_CATEGORIA ASC) AS DENSE_RANK_CATEGORIA,
	ID_CATEGORIA,
	NOME_PRODUTO
FROM PRODUTOS;


-- ROW_NUMBER
-- RETORNA O NÚMERO SEQUENCIAL DE UMA LINHA EM UMA PARTIÇÃO DE UM CONJUNTO DE RESULTADOS,
-- INICIANDO EM 1 PARA A PRIMEIRA LINHA DE CADA PARTIÇÃO.

-- ROW_NUMBER (EXEMPLO)
SELECT ROW_NUMBER() OVER (ORDER BY ID_CATEGORIA ASC) AS ROW_NUMBER_CATEGORIA,
	ID_CATEGORIA,
	NOME_PRODUTO
FROM PRODUTOS;