USE SALES;

-- CURSORES (EXEMPLO 2 - UPDATE)

-- CRIANDO TABELA CADASTRO PARA EXEMPLO
SELECT A.ID_CLIENTE,
	   A.NOME_CLIENTE,
	   A.ENDERECO,
	   A.NUMERO,
	   CAST('' AS VARCHAR (150)) ENDERECO_COMPLETO
	   INTO CADASTRO
FROM CLIENTE AS A;
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO;
-- DECLARANDO VARIÁVEIS
DECLARE @ID_CLIENTE INT,
		@NOME_CLIENTE VARCHAR(50),
		@ENDERECO VARCHAR(150),
		@NUMERO VARCHAR(10),
		@ENDERECO_COMPLETO VARCHAR(150)
-- DECLARANDO CURSOR
DECLARE MEU_CURSOR2
CURSOR FOR SELECT ID_CLIENTE,
				  NOME_CLIENTE,
				  ENDERECO,
				  NUMERO
FROM CLIENTE
-- ABRINDO CURSOR
OPEN MEU_CURSOR2
-- LENDO A PRÓXIMA LINHA
FETCH NEXT FROM MEU_CURSOR2 INTO @ID_CLIENTE, @NOME_CLIENTE, @ENDERECO, @NUMERO
-- PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
WHILE @@FETCH_STATUS = 0
	BEGIN
	UPDATE CADASTRO
	SET ENDERECO_COMPLETO = @ENDERECO + ', ' + @NUMERO
	WHERE ID_CLIENTE = @ID_CLIENTE
-- LENDO A PRÓXIMA LINHA
	FETCH NEXT FROM MEU_CURSOR2 INTO @ID_CLIENTE, @NOME_CLIENTE, @ENDERECO, @NUMERO
	END
-- FECHANDO CURSOR
CLOSE MEU_CURSOR2
-- FINALIZANDO CURSOR
DEALLOCATE MEU_CURSOR2
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO;
-- EXCLUINDO TABELA CADASTRO CRIADA PARA EXEMPLO
DROP TABLE CADASTRO;