USE SALES;

-- CURSORES (EXEMPLO 5 - SCROLL)

-- CRIANDO TABELA CADASTRO PARA EXEMPLO
CREATE TABLE CADASTRO
	(
	ID_CLIENTE INT NOT NULL,
	NOME_CLIENTE VARCHAR(50) NOT NULL,
	);
-- INSERINDO DADOS
INSERT INTO CADASTRO VALUES
(1, 'DIANA'),
(2, 'MARIE'),
(3, 'SARAH'),
(4, 'SUELY'),
(5, 'TALIA'),
(6, 'DAVID'),
(7, 'PETER'),
(8, 'ETHAN'),
(9, 'ISAAC'),
(10, 'HENRY');
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO;
-- DECLARANDO CURSOR
DECLARE MEU_CURSOR5
SCROLL CURSOR FOR SELECT ID_CLIENTE,
						 NOME_CLIENTE
FROM CADASTRO
-- ABRINDO CURSOR
OPEN MEU_CURSOR5

-- RETORNA A QUANTIDADE DE LINHAS
SELECT @@CURSOR_ROWS;

-- RETORNA O PRIMEIRO REGISTRO DO CURSOR
FETCH ABSOLUTE 1 FROM MEU_CURSOR5;

-- RETORNA O PRÓXIMO REGISTRO DO CURSOR
FETCH NEXT FROM MEU_CURSOR5;

-- RETORNA O ÚLTIMO REGISTRO DO CURSOR
FETCH LAST FROM MEU_CURSOR5;

-- RETORNA O REGISTRO ANTERIOR AO REGISTRO ATUAL DO CURSOR
FETCH PRIOR FROM MEU_CURSOR5;

-- RETORNA PARA A SEGUNDA LINHA DO CURSOR
FETCH ABSOLUTE 2 FROM MEU_CURSOR5;

-- AVANÇA TRÊS REGISTROS EM RELAÇÃO AO REGISTRO ATUAL DO CURSOR
FETCH RELATIVE 3 FROM MEU_CURSOR5;

-- RETROCEDE DOIS REGISTROS EM RELAÇÃO AO REGISTRO ATUAL DO CURSOR
FETCH RELATIVE -2 FROM MEU_CURSOR5;

-- FECHANDO CURSOR
CLOSE MEU_CURSOR5
-- FINALIZANDO CURSOR
DEALLOCATE MEU_CURSOR5
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO;
-- EXCLUINDO TABELA CADASTRO_CPF CRIADA PARA EXEMPLO
DROP TABLE CADASTRO;