USE SALES;

-- CURSORES (EXEMPLO 4 - UPDATE CONDICIONAL)

-- CRIANDO TABELA CADASTRO_CPF PARA EXEMPLO
CREATE TABLE CADASTRO_CPF
	(
	ID_CLIENTE INT NOT NULL PRIMARY KEY,
	NOME_CLIENTE VARCHAR(50) NOT NULL,
	CPF_CLIENTE VARCHAR(20)
	);
-- INSERINDO DADOS
INSERT INTO CADASTRO_CPF VALUES
(1, 'DIANA', 12345),
(2, 'MARIE', 56789),
(3, 'SARAH', NULL),
(4, 'SUELY', NULL),
(5, 'TALIA', NULL);
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO_CPF;
-- DECLARANDO VARIÁVEIS
DECLARE @ID_CLIENTE INT,
		@NOME_CLIENTE VARCHAR(50),
		@CPF_CLIENTE VARCHAR(20)
-- DECLARANDO CURSOR
DECLARE MEU_CURSOR4
CURSOR FOR SELECT ID_CLIENTE,
				  NOME_CLIENTE,
				  CPF_CLIENTE
FROM CADASTRO_CPF
-- ABRINDO CURSOR
OPEN MEU_CURSOR4
-- LENDO A PRÓXIMA LINHA
FETCH NEXT FROM MEU_CURSOR4 INTO @ID_CLIENTE, @NOME_CLIENTE, @CPF_CLIENTE
-- PERCORRENDO LINHAS DO CURSOR (ENQUANTO HOUVEREM)
WHILE @@FETCH_STATUS = 0
	BEGIN
	IF (@CPF_CLIENTE IS NULL)
		BEGIN
		UPDATE CADASTRO_CPF SET CPF_CLIENTE = 'CPF NÃO CADASTRADO'
		WHERE CPF_CLIENTE IS NULL
		AND ID_CLIENTE = @ID_CLIENTE
		END
-- LENDO A PRÓXIMA LINHA
		FETCH NEXT FROM MEU_CURSOR4 INTO @ID_CLIENTE, @NOME_CLIENTE, @CPF_CLIENTE
	END
-- FECHANDO CURSOR
CLOSE MEU_CURSOR4
-- FINALIZANDO CURSOR
DEALLOCATE MEU_CURSOR4
-- VERIFICANDO DADOS
SELECT * FROM CADASTRO_CPF;
-- EXCLUINDO TABELA CADASTRO_CPF CRIADA PARA EXEMPLO
DROP TABLE CADASTRO_CPF;