USE SALES;

-- TEMPTABLE
-- UMA TABELA TEMPORÁRIA SÓ EXISTE ENQUANTO A CONEXÃO RESPONSÁVEL PELA SUA CRIAÇÃO ESTIVER ATIVA.
-- NO MOMENTO DA DESCONEXÃO, AS TABELAS TEMPORÁRIAS REMANESCENTES SÃO DROPADAS AUTOMATICAMENTE.
-- PODEM SER CLASSIFICADAS COMO LOCAIS E GLOBAIS:
-- LOCAIS: SÃO CRIADAS COM O PREFIXO # E POSSUEM VISIBILIDADE RESTRITA PARA A CONEXÃO RESPONSÁVEL POR SUA CRIAÇÃO.
-- GLOBAIS: SÃO CRIADAS COM O PREFIXO ## E POSSUEM VISIBILIDADE PARA TODAS AS CONEXÕES.

-- CRIANDO TABELA TEMPORÁRIA COM BASE EM UMA EXISTENTE
SELECT * INTO #SALARIOTEMP FROM SALARIO;

-- VERIFICANDO REGISTROS
SELECT * FROM #SALARIOTEMP;


-- CRIANDO TABELA TEMPORÁRIA COM BASE EM UMA OUTRA TABELA TEMPORÁRIA EXISTENTE
SELECT MATRICULA, SALARIO_FIXO INTO #SALARIOTEMP2 FROM #SALARIOTEMP;

-- VERIFICANDO REGISTROS
SELECT * FROM #SALARIOTEMP2;