USE SALES;
GO

-- CRIANDO TABELA PARA EXEMPLOS
CREATE TABLE FORNECEDORES
	(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ENDERECO VARCHAR(60) NOT NULL,
	TAXA_ENTREGA DECIMAL(10,2) NOT NULL
	);


-- EXEMPLO SELECT
SELECT * FROM FORNECEDORES;
-- EXEMPLO SELECT
SELECT NOME, ENDERECO FROM FORNECEDORES; 
-- EXEMPLO SELECT
SELECT NOME,ENDERECO AS CONTATO FROM FORNECEDORES;

-- EXEMPLO INSERT
INSERT INTO FORNECEDORES VALUES
('Loja HardStore', 'Rua Santa Ifigênia, 300', '100'),
('Loja InfoStore', 'Rua Santa Ifigênia, 400', '110'),
('Loja GameHouse', 'Rua Santa Ifigênia, 500', '120');
-- EXEMPLO INSERT
INSERT INTO FORNECEDORES (NOME, ENDERECO, TAXA_ENTREGA) VALUES
('ClubGamer', 'Rua Santa Ifigênia, 600', '130');


-- EXEMPLO UPDATE
UPDATE FORNECEDORES SET TAXA_ENTREGA = '150' 
WHERE  ID = '1';
-- EXEMPLO UPDATE COM AUMENTO DE 50% SOBRE A TAXA DE ENTREGA ATUAL
UPDATE FORNECEDORES SET TAXA_ENTREGA = TAXA_ENTREGA*1.5 
WHERE  ID = '1'; 
-- EXEMPLO UPDATE COM MAIS DE UM CAMPO
UPDATE FORNECEDORES SET TAXA_ENTREGA = TAXA_ENTREGA*1.5, ENDERECO='Rua Santa Ifigênia, 2000'
WHERE  ID = '1'; 


-- EXEMPLO DELETE
DELETE FORNECEDORES 
WHERE ID = '1';



