-- CRIANDO TABELA DE EXEMPLO
CREATE TABLE CADASTRO
		(
		 NOME VARCHAR(50) NOT NULL,
		 DOCTO VARCHAR(20) NOT NULL
		 );

-- INICIANDO TRANSAÇÃO
BEGIN TRANSACTION;
-- INSERINDO REGISTROS
INSERT INTO CADASTRO VALUES ('Cris', '123456789');
INSERT INTO CADASTRO VALUES ('Caio', '123456789');
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;
-- RESTAURANDO AO ESTADO ANTERIOR DESDE O ÚLTIMO COMMIT
ROLLBACK;
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;


-- INICIANDO TRANSAÇÃO
BEGIN TRANSACTION;
-- INSERINDO REGISTROS
INSERT INTO CADASTRO VALUES ('Cris', '123456789');
INSERT INTO CADASTRO VALUES ('Caio', '123456789');
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;
-- SALVANDO A TRANSAÇÃO REALIZADA
COMMIT TRANSACTION;
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;


-- LIMPANDO A TABELA DE EXEMPLO
DELETE FROM CADASTRO;
-- INICIANDO TRANSAÇÃO
BEGIN TRANSACTION;
-- INSERINDO REGISTROS
INSERT INTO CADASTRO VALUES ('Cris', '123456789');
INSERT INTO CADASTRO VALUES ('Caio', '123456789');
-- CRIANDO UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION A1;
-- INSERINDO REGISTROS
INSERT INTO CADASTRO VALUES ('Alex', '123456789');
-- CRIANDO UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION A2;
-- INSERINDO REGISTROS
INSERT INTO CADASTRO VALUES ('José', '123456789');
-- CRIANDO UM PONTO DE RECUPERAÇÃO
SAVE TRANSACTION A3;


-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;
-- RESTAURANDO A TABELA ATÉ O PONTO A2
ROLLBACK TRANSACTION A2;
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;


-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;
-- RESTAURANDO A TABELA ATÉ O PONTO A3
ROLLBACK TRANSACTION A3;
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;


-- SALVANDO A TRANSAÇÃO REALIZADA
COMMIT TRANSACTION;
-- VERIFICANDO REGISTROS
SELECT * FROM CADASTRO;