USE SALES;

-- TRY_CATCH
-- IMPLEMENTA TRATAMENTO DE ERROS E EXCEÇÕES. 
-- UM GRUPO DE INSTRUÇÕES PODE SER INCLUÍDO EM UM BLOCO TRY.
-- SE OCORRER UM ERRO NO BLOCO TRY, O CONTROLE PASSARÁ PARA OUTRO GRUPO DE INSTRUÇÕES QUE ESTÁ INCLUÍDO EM UM BLOCO CATCH.

BEGIN TRY
	SELECT 10/0;
END TRY
BEGIN CATCH
	SELECT ERROR_NUMBER() AS ERRORNUMBER, -- RETORNA O NÚMERO DO ERRO
		   ERROR_SEVERITY() AS ERRORSEVERITY, -- RETORNA A SEVERIDADE DO ERRO
		   ERROR_STATE() AS ERRORSTATE, -- RETORNA O NÚMERO DO ESTADO DO ERRO
		   ERROR_PROCEDURE() AS ERRORPROCEDURE, -- RETORNA O NOME DA PROCEDURE OU TRIGGER NO QUAL OCORREU O ERRO
		   ERROR_LINE() AS ERRORLINE, -- RETORNA O NÚMERO DE LINHAS DENTRO DA ROTINA QUE CAUSOU O ERRO
		   ERROR_MESSAGE() AS ERRORMESSAGE; -- RETORNA O TEXTO COMPLETO DA MENSAGEM DO ERRO
END CATCH;