USE SALES;

-- VIEW
-- A VIEW PODE SER DEFINIDA COMO UMA TABELA VIRTUAL COMPOSTA POR LINHAS E COLUNAS DE DADOS VINDOS DE TABELAS RELACIONADAS EM UMA QUERY.
-- AS LINHAS E COLUNAS DA VIEW SÃO GERADAS DINAMICAMENTE NO MOMENTO EM QUE É FEITA UMA REFERÊNCIA A ELA.
-- A VIEW PODE VIR DE UMA OU MAIS TABELAS, OU ATÉ MESMO DE OUTRA VIEW.
-- TRATA-SE DE UM TIPO DE OBJETO DE CARÁTER PERMANENTE.

-- CRIANDO VIEW
CREATE VIEW V_PRODUTOS AS
	SELECT A.ID_PROD,
		   A.NOME_PRODUTO,
		   A.PRECO,
		   B.NOME_CATEGORIA
	FROM PRODUTOS AS A
	INNER JOIN CATEGORIA AS B
	ON A.ID_CATEGORIA = B.ID_CATEGORIA;

-- VERIFICANDO VIEW
SELECT * FROM V_PRODUTOS
WHERE PRECO > 500
ORDER BY PRECO ASC;