
-- DYNAMIC DATA MASKING
-- O DDM (DYNAMIC DATA MASKING) LIMITA A EXPOSIÇÃO DE DADOS CONFIDENCIAIS APLICANDO UMA MÁSCARA PARA USUÁRIOS SEM PRIVILÉGIOS. ELE PODE SER USADO PARA SIMPLIFICAR BASTANTE O DESIGN E A CODIFICAÇÃO DE SEGURANÇA EM SEU APLICATIVO.
-- AJUDA A IMPEDIR O ACESSO NÃO AUTORIZADO A DADOS CONFIDENCIAIS, PERMITINDO QUE OS CLIENTES ESPECIFIQUEM A QUANTIDADE DE DADOS CONFIDENCIAIS A REVELAR, COM IMPACTO MÍNIMO SOBRE A CAMADA DE APLICATIVO.
-- PODE SER CONFIGURADO EM CAMPOS DE BANCO DE DADOS DESIGNADOS PARA OCULTAR DADOS CONFIDENCIAIS NOS CONJUNTOS DE RESULTADOS DE CONSULTAS. COM DDM, OS DADOS NO BANCO DE DADOS NÃO SÃO ALTERADOS.

-- EXEMPLO
-- CRIANDO DATABASE  DE EXEMPLO
CREATE DATABASE DB_LGPD;
USE DB_LGPD;

-- CRIANDO TABELA  DE EXEMPLO
CREATE TABLE CLIENTE
		(
		ID_CLIENTE INT IDENTITY PRIMARY KEY,
		PRIMEIRO_NOME VARCHAR(100) MASKED WITH (FUNCTION = 'PARTIAL(1, "XXXXXXX", 0)') NOT NULL,
		ULTIMO_NOME VARCHAR(100) NOT NULL,
		TELEFONE VARCHAR(12) MASKED WITH (FUNCTION = 'DEFAULT()') NULL,
		EMAIL VARCHAR(100) MASKED WITH (FUNCTION = 'EMAIL()') NULL,
		CARTAO VARCHAR(20) NOT NULL,
		SALARIO DECIMAL(10, 2) NOT NULL
		);

-- INSERINDO REGISTROS NA TABELA
INSERT CLIENTE VALUES
('ALBERT', 'EINSTEIN', '11-9999-0000', 'albert@teste.com', '1111-2222-3333-4444', 35000),
('CHARLES', 'DARWIN', '11-9999-0000', 'charles@teste.com', '2222-3333-4444-5555', 25000),
('ISAAC', 'NEWTON', '11-9999-0000', 'isaac@teste.com', '3333-4444-5555-6666', 15000);

-- VERIFICANDO REGISTROS INSERIDOS NA TABELA
SELECT * FROM CLIENTE;

-- IDENTIFICANDO OS CAMPOS COM MÁSCARA
SELECT C.NAME AS COLUMN_NAME,
	   T.NAME AS TABLE_NAME,
	   C.IS_MASKED,
	   C.MASKING_FUNCTION
FROM SYS.MASKED_COLUMNS AS C
	JOIN SYS.TABLES AS T
	ON C.[OBJECT_ID] = T.[OBJECT_ID]
WHERE IS_MASKED = 1;

-- ADICIONANDO MÁSCARAS NA TABELA EXISTENTE
-- MÁSCARA ULTIMO_NOME
ALTER TABLE CLIENTE ALTER COLUMN ULTIMO_NOME ADD MASKED WITH (FUNCTION = 'PARTIAL(2, "XXXXXXX", 0)');
-- MÁSCARA TELEFONE
ALTER TABLE CLIENTE ALTER COLUMN TELEFONE ADD MASKED WITH (FUNCTION = 'PARTIAL(5, "XXXXXXX", 0)');
-- MÁSCARA CARTAO
ALTER TABLE CLIENTE ALTER COLUMN CARTAO ADD MASKED WITH (FUNCTION = 'PARTIAL(0, "XXXX-XXXX-XXXX-", 4)');
-- MÁSCARA SALARIO
ALTER TABLE CLIENTE ALTER COLUMN SALARIO ADD MASKED WITH (FUNCTION = 'DEFAULT()');